import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export interface ComparisonData {
  first: any;
  second: any;
  summary: string[];
}

export const exportComparisonPDF = ({
  first,
  second,
  summary,
}: ComparisonData) => {
  const pdf = new jsPDF("p", "mm", "a4");

  // =============================
  // Header
  // =============================

  pdf.setFillColor(37, 99, 235);
  pdf.rect(0, 0, 210, 28, "F");

  pdf.setTextColor(255);
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(22);
  pdf.text("RankFlow", 20, 15);

  pdf.setFontSize(11);
  pdf.text("SEO Comparison Report", 20, 23);

  pdf.setTextColor(0);

  // =============================
  // Website Details
  // =============================

  pdf.setFontSize(16);
  pdf.setFont("helvetica", "bold");
  pdf.text("Compared Websites", 20, 42);

  pdf.setFontSize(12);
  pdf.setFont("helvetica", "normal");

  pdf.text(`Website A : ${first.url}`, 20, 52);
  pdf.text(`Website B : ${second.url}`, 20, 60);

  pdf.text(
    `Generated : ${new Date().toLocaleString()}`,
    20,
    68
  );

  // =============================
  // Comparison Table
  // =============================

  autoTable(pdf, {
    startY: 78,

    head: [["Metric", "Analysis 1", "Analysis 2"]],

    body: [
      [
        "Overall SEO",
        first.overallScore,
        second.overallScore,
      ],

      [
        "SEO",
        first.categories.seo,
        second.categories.seo,
      ],

      [
        "Performance",
        first.categories.performance,
        second.categories.performance,
      ],

      [
        "Accessibility",
        first.categories.accessibility,
        second.categories.accessibility,
      ],

      [
        "Best Practices",
        first.categories.bestPractices,
        second.categories.bestPractices,
      ],

      [
        "FCP",
        first.metrics.fcp,
        second.metrics.fcp,
      ],

      [
        "LCP",
        first.metrics.lcp,
        second.metrics.lcp,
      ],

      [
        "CLS",
        first.metrics.cls,
        second.metrics.cls,
      ],

      [
        "TBT",
        first.metrics.tbt,
        second.metrics.tbt,
      ],
    ],

    headStyles: {
      fillColor: [37, 99, 235],
    },
  });

  // =============================
  // AI Summary
  // =============================

  const lastY =
    (pdf as any).lastAutoTable.finalY + 15;

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(16);

  pdf.text("AI Summary", 20, lastY);

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(12);

  let y = lastY + 10;

  summary.forEach((line) => {
    pdf.text(`• ${line}`, 20, y);
    y += 8;
  });

  // =============================
  // Footer
  // =============================

  pdf.setFontSize(10);
  pdf.setTextColor(120);

  pdf.text(
    "Generated by RankFlow",
    20,
    288
  );

  pdf.text(
    new Date().toLocaleDateString(),
    170,
    288
  );

  pdf.save("RankFlow_Comparison_Report.pdf");
};