import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface Competitor {
  position: number;
  domain: string;
  title: string;
}

interface ReportData {
  keyword: string;
  domain: string;
  currentPosition: number | null;
  bestPosition: number | null;
  positionChange: number;
  currentPage: number | null;
  lastChecked: string | null;
  historyCount: number;
  competitors: Competitor[];
}

export const exportPDF = (data: ReportData) => {
  const pdf = new jsPDF("p", "mm", "a4");

  // =========================
  // HEADER
  // =========================

  pdf.setFillColor(41, 98, 255);
  pdf.rect(0, 0, 210, 28, "F");

  pdf.setTextColor(255);
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(22);
  pdf.text("RankFlow SEO Report", 20, 18);

  pdf.setFontSize(10);
  pdf.text(
    `Generated : ${new Date().toLocaleString()}`,
    20,
    24
  );

  pdf.setTextColor(0);

  // =========================
  // TITLE
  // =========================

  pdf.setFontSize(18);
  pdf.setFont("helvetica", "bold");

  pdf.text("Executive Summary", 20, 42);

  // =========================
  // SUMMARY TABLE
  // =========================

  autoTable(pdf, {
    startY: 48,
    head: [["Metric", "Value"]],
    body: [
      ["Keyword", data.keyword],
      ["Domain", data.domain],
      [
        "Current Position",
        data.currentPosition
          ? `#${data.currentPosition}`
          : "Not Ranked",
      ],
      [
        "Best Position",
        data.bestPosition
          ? `#${data.bestPosition}`
          : "-",
      ],
      [
        "Position Change",
        data.positionChange.toString(),
      ],
      [
        "Google Page",
        data.currentPage
          ? `Page ${data.currentPage}`
          : "-",
      ],
      [
        "Last Checked",
        data.lastChecked
          ? new Date(
              data.lastChecked
            ).toLocaleString()
          : "-",
      ],
      [
        "Ranking Records",
        data.historyCount.toString(),
      ],
    ],
    headStyles: {
      fillColor: [41, 98, 255],
    },
  });

  // =========================
  // SEO SCORE
  // =========================

  let score = 40;

  if (
    data.currentPosition &&
    data.currentPosition <= 10
  )
    score += 30;

  if (
    data.currentPosition &&
    data.currentPosition <= 3
  )
    score += 20;

  if (
    data.positionChange > 0
  )
    score += 10;

  if (score > 100)
    score = 100;

  pdf.setFontSize(18);

  // get last autoTable Y position with proper typing
  const lastTableFinalY = (
    pdf as jsPDF & { lastAutoTable?: { finalY: number } }
  ).lastAutoTable?.finalY ?? 48;

  pdf.text(
    "SEO Performance",
    20,
    lastTableFinalY + 20
  );

  pdf.setFontSize(32);

  pdf.setTextColor(34, 197, 94);

  pdf.text(
    `${score}/100`,
    20,
    lastTableFinalY + 38
  );

  pdf.setTextColor(0);

  pdf.setFontSize(12);

  pdf.text(
    "Overall SEO Score",
    20,
    lastTableFinalY + 45
  );

  // =========================
  // NEW PAGE
  // =========================

  pdf.addPage();

  pdf.setFontSize(20);

  pdf.text(
    "Top Competitors",
    20,
    20
  );

  autoTable(pdf, {
    startY: 28,
    head: [["Rank", "Domain", "Title"]],
    body: data.competitors.map(
      (c) => [
        c.position,
        c.domain,
        c.title,
      ]
    ),
    headStyles: {
      fillColor: [41, 98, 255],
    },
  });

  // =========================
  // RECOMMENDATIONS
  // =========================

  pdf.addPage();

  pdf.setFontSize(20);

  pdf.text(
    "SEO Recommendations",
    20,
    20
  );

  pdf.setFontSize(12);

  const recommendations = [
    "Improve page loading speed.",
    "Optimize meta title and description.",
    "Increase high-quality backlinks.",
    "Improve internal linking.",
    "Add structured data (Schema.org).",
    "Optimize Core Web Vitals.",
    "Publish fresh SEO content regularly.",
    "Monitor rankings weekly.",
  ];

  recommendations.forEach(
    (item, index) => {
      pdf.text(
        `• ${item}`,
        20,
        35 + index * 10
      );
    }
  );

  // =========================
  // FOOTER
  // =========================

  const pages =
    pdf.getNumberOfPages();

  for (
    let i = 1;
    i <= pages;
    i++
  ) {
    pdf.setPage(i);

    pdf.setFontSize(10);

    pdf.setTextColor(120);

    pdf.text(
      "Generated by RankFlow",
      20,
      290
    );

    pdf.text(
      `Page ${i} of ${pages}`,
      170,
      290
    );
  }

  pdf.save(
    `${data.keyword.replace(
      /\s+/g,
      "_"
    )}_SEO_Report.pdf`
  );
};